
const encoder=new TextEncoder();
const ADMIN_EMAILS=["haneen.jalal@gmail.com","omar.manaa@gmail.com"];
const json=(data,status=200,headers={})=>new Response(JSON.stringify(data),{status,headers:{"content-type":"application/json; charset=utf-8","cache-control":"no-store",...headers}});
const object=v=>v&&typeof v==="object"&&!Array.isArray(v);
function merge(base,saved){if(Array.isArray(base))return Array.isArray(saved)?saved:base;if(!object(base))return saved===undefined||saved===null?base:saved;const out={...base};if(!object(saved))return out;for(const [k,v] of Object.entries(saved))out[k]=k in base?merge(base[k],v):v;return out}
async function defaults(env){return (await env.ASSETS.fetch(new Request("https://assets.local/default-content.json"))).json()}
async function getContent(env){const base=await defaults(env),row=await env.DB.prepare("SELECT content FROM site_content WHERE id=1").first();if(!row?.content)return base;try{return merge(base,JSON.parse(row.content))}catch{return base}}
async function saveContent(env,value){const data=merge(await defaults(env),value);data.schemaVersion=7;await env.DB.prepare("INSERT INTO site_content(id,content,updated_at) VALUES(1,?,datetime('now')) ON CONFLICT(id) DO UPDATE SET content=excluded.content,updated_at=datetime('now')").bind(JSON.stringify(data)).run();return data}
const hex=b=>[...new Uint8Array(b)].map(x=>x.toString(16).padStart(2,"0")).join("");const fromHex=h=>new Uint8Array((h.match(/.{1,2}/g)||[]).map(x=>parseInt(x,16)));function randomHex(n=32){const b=new Uint8Array(n);crypto.getRandomValues(b);return hex(b)}async function sha256(v){return hex(await crypto.subtle.digest("SHA-256",encoder.encode(v)))}
async function hashPassword(password,salt=randomHex(16),iterations=120000){const key=await crypto.subtle.importKey("raw",encoder.encode(password),"PBKDF2",false,["deriveBits"]);const bits=await crypto.subtle.deriveBits({name:"PBKDF2",hash:"SHA-256",salt:fromHex(salt),iterations},key,256);return {hash:hex(bits),salt,iterations}}
function equal(a,b){if(!a||!b||a.length!==b.length)return false;let x=0;for(let i=0;i<a.length;i++)x|=a.charCodeAt(i)^b.charCodeAt(i);return x===0}const email=v=>String(v||"").trim().toLowerCase();const superAdmin=e=>ADMIN_EMAILS.includes(email(e));const strong=p=>typeof p==="string"&&p.length>=12&&/[A-Z]/.test(p)&&/[a-z]/.test(p)&&/[0-9]/.test(p);const validEmail=e=>/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(e);
function cookies(req){const o={};for(const p of (req.headers.get("Cookie")||"").split(";")){const [k,...v]=p.trim().split("=");if(k)o[k]=decodeURIComponent(v.join("="))}return o}const sessionCookie=(token,age=28800)=>`br_session=${encodeURIComponent(token)}; Path=/; HttpOnly; Secure; SameSite=Strict; Max-Age=${age}`;const clearCookie=()=>"br_session=; Path=/; HttpOnly; Secure; SameSite=Strict; Max-Age=0";
async function session(req,env){const token=cookies(req).br_session;if(!token)return null;return env.DB.prepare("SELECT s.id session_id,s.csrf_token,u.id,u.email,u.name,u.role,u.active FROM sessions s JOIN users u ON u.id=s.user_id WHERE s.token_hash=? AND s.expires_at>datetime('now')").bind(await sha256(token)).first().then(r=>r?.active?r:null)}function csrf(req,s){const t=req.headers.get("x-csrf-token");return !!t&&equal(t,s.csrf_token)}
async function auth(req,env,url){
 if(url.pathname==="/api/auth/setup"&&req.method==="POST"){const count=await env.DB.prepare("SELECT COUNT(*) total FROM users").first();if(Number(count?.total||0)>0)return json({error:"Setup is already complete."},409);const b=await req.json(),e=email(b.email);if(b.token!==env.ADMIN_SETUP_TOKEN)return json({error:"Invalid setup token."},403);if(!superAdmin(e))return json({error:"Use an approved administrator email."},403);if(!strong(b.password))return json({error:"Use at least 12 characters with uppercase, lowercase and a number."},400);const h=await hashPassword(b.password);await env.DB.prepare("INSERT INTO users(id,email,name,role,password_hash,password_salt,password_iterations,active) VALUES(?,?,?,?,?,?,?,1)").bind(crypto.randomUUID(),e,String(b.name||"Administrator").trim(),"admin",h.hash,h.salt,h.iterations).run();return json({ok:true})}
 if(url.pathname==="/api/auth/login"&&req.method==="POST"){const b=await req.json(),e=email(b.email),u=await env.DB.prepare("SELECT * FROM users WHERE email=?").bind(e).first();if(!u?.active)return json({error:"Invalid email or password."},401);const h=await hashPassword(String(b.password||""),u.password_salt,u.password_iterations);if(!equal(h.hash,u.password_hash))return json({error:"Invalid email or password."},401);const token=randomHex(),csrfToken=randomHex(24);await env.DB.prepare("INSERT INTO sessions(id,user_id,token_hash,csrf_token,expires_at) VALUES(?,?,?,?,datetime('now','+8 hours'))").bind(crypto.randomUUID(),u.id,await sha256(token),csrfToken).run();return json({ok:true},200,{"set-cookie":sessionCookie(token)})}
 if(url.pathname==="/api/auth/me"&&req.method==="GET"){const s=await session(req,env);return s?json({id:s.id,email:s.email,name:s.name,role:s.role,csrfToken:s.csrf_token,canManageUsers:superAdmin(s.email)}):json({error:"Unauthorized"},401)}
 if(url.pathname==="/api/auth/logout"&&req.method==="POST"){const s=await session(req,env);if(s)await env.DB.prepare("DELETE FROM sessions WHERE id=?").bind(s.session_id).run();return json({ok:true},200,{"set-cookie":clearCookie()})}
 return null
}
async function users(req,env,url,s){
 if(!superAdmin(s.email))return json({error:"Only approved administrator emails can manage users."},403);
 if(url.pathname==="/api/users"&&req.method==="GET"){const r=await env.DB.prepare("SELECT id,email,name,role,active,created_at,updated_at FROM users ORDER BY created_at").all();return json({users:r.results||[]})}
 if(url.pathname==="/api/users"&&req.method==="POST"){try{const b=await req.json(),e=email(b.email),name=String(b.name||"").trim(),role=b.role==="admin"?"admin":"editor",password=String(b.password||"");if(!validEmail(e))return json({error:"Enter a valid email address."},400);if(!name)return json({error:"Enter the user's name."},400);if(!strong(password))return json({error:"Password must be at least 12 characters and include uppercase, lowercase and a number."},400);const h=await hashPassword(password),id=crypto.randomUUID();await env.DB.prepare("INSERT INTO users(id,email,name,role,password_hash,password_salt,password_iterations,active) VALUES(?,?,?,?,?,?,?,1)").bind(id,e,name,role,h.hash,h.salt,h.iterations).run();const user=await env.DB.prepare("SELECT id,email,name,role,active,created_at,updated_at FROM users WHERE id=?").bind(id).first();return json({ok:true,user},201)}catch(error){const message=String(error?.message||error);console.error("Create user failed",message);if(message.toLowerCase().includes("unique"))return json({error:"A user with this email already exists."},409);return json({error:"Could not create user.",details:message},500)}}
 let m=url.pathname.match(/^\/api\/users\/([^/]+)\/password$/);if(m&&req.method==="PUT"){const b=await req.json();if(!strong(b.password))return json({error:"Password does not meet requirements."},400);const h=await hashPassword(b.password);await env.DB.batch([env.DB.prepare("UPDATE users SET password_hash=?,password_salt=?,password_iterations=?,updated_at=datetime('now') WHERE id=?").bind(h.hash,h.salt,h.iterations,m[1]),env.DB.prepare("DELETE FROM sessions WHERE user_id=?").bind(m[1])]);return json({ok:true})}
 m=url.pathname.match(/^\/api\/users\/([^/]+)\/status$/);if(m&&req.method==="PUT"){const b=await req.json();await env.DB.prepare("UPDATE users SET active=?,updated_at=datetime('now') WHERE id=?").bind(b.active?1:0,m[1]).run();return json({ok:true})}return null
}
const IMAGE_TYPES=new Set(["image/jpeg","image/png","image/webp","image/avif"]);function galleryItem(row,origin){return {id:row.id,title:row.title||"",altText:row.alt_text||"",displayOrder:Number(row.display_order)||0,active:Boolean(row.active),createdAt:row.created_at||"",url:`${origin}/media/gallery/${encodeURIComponent(row.id)}`}}async function listGallery(env,origin,all=false){const r=await env.DB.prepare(all?"SELECT * FROM gallery_images ORDER BY display_order,created_at DESC":"SELECT * FROM gallery_images WHERE active=1 ORDER BY display_order,created_at DESC").all();return (r.results||[]).map(x=>galleryItem(x,origin))}
async function galleryMedia(env,id){const row=await env.DB.prepare("SELECT object_key,content_type FROM gallery_images WHERE id=?").bind(id).first();if(!row)return new Response("Not found",{status:404});const object=await env.GALLERY.get(row.object_key);if(!object)return new Response("Not found",{status:404});const headers=new Headers();object.writeHttpMetadata(headers);headers.set("content-type",row.content_type);headers.set("etag",object.httpEtag);headers.set("cache-control","public,max-age=3600,stale-while-revalidate=86400");return new Response(object.body,{headers})}
async function galleryAdmin(req,env,url){if(!env.GALLERY)return json({error:"R2 binding GALLERY is not configured."},500);if(url.pathname==="/api/admin/gallery"&&req.method==="GET")return json({images:await listGallery(env,url.origin,true)});if(url.pathname==="/api/admin/gallery/upload"&&req.method==="POST"){const form=await req.formData(),file=form.get("image");if(!(file instanceof File))return json({error:"No image received."},400);if(!IMAGE_TYPES.has(file.type))return json({error:"Use JPEG, PNG, WebP or AVIF."},400);if(file.size>20*1024*1024)return json({error:"Maximum image size is 20 MB."},400);const id=crypto.randomUUID(),key=`gallery/${id}`;await env.GALLERY.put(key,file.stream(),{httpMetadata:{contentType:file.type}});try{const max=await env.DB.prepare("SELECT COALESCE(MAX(display_order),0) value FROM gallery_images").first();await env.DB.prepare("INSERT INTO gallery_images(id,object_key,title,alt_text,display_order,active,content_type,size_bytes) VALUES(?,?,?,?,?,1,?,?)").bind(id,key,String(form.get("title")||"").slice(0,160),String(form.get("altText")||"").slice(0,240),Number(max?.value||0)+10,file.type,file.size).run()}catch(e){
  await env.GALLERY.delete(key);
  console.error("Gallery metadata insert failed:",e?.stack||e);
  return json({
    error:"The photo reached storage, but its gallery record could not be saved.",
    details:String(e?.message||e)
  },500)
}const row=await env.DB.prepare("SELECT * FROM gallery_images WHERE id=?").bind(id).first();return json({ok:true,image:galleryItem(row,url.origin)},201)}let m=url.pathname.match(/^\/api\/admin\/gallery\/([^/]+)$/);if(m&&req.method==="PUT"){const b=await req.json();await env.DB.prepare("UPDATE gallery_images SET title=?,alt_text=?,display_order=?,active=?,updated_at=datetime('now') WHERE id=?").bind(String(b.title||"").slice(0,160),String(b.altText||"").slice(0,240),Number(b.displayOrder)||0,b.active?1:0,m[1]).run();return json({ok:true})}if(m&&req.method==="DELETE"){const row=await env.DB.prepare("SELECT object_key FROM gallery_images WHERE id=?").bind(m[1]).first();if(!row)return json({error:"Image not found."},404);await env.GALLERY.delete(row.object_key);await env.DB.prepare("DELETE FROM gallery_images WHERE id=?").bind(m[1]).run();return json({ok:true})}return null}
export default{async fetch(req,env){const url=new URL(req.url);if(url.pathname==="/api/content"&&req.method==="GET")return json(await getContent(env));if(url.pathname==="/api/gallery"&&req.method==="GET")return json({images:await listGallery(env,url.origin)});if(url.pathname.startsWith("/media/gallery/")&&req.method==="GET")return galleryMedia(env,decodeURIComponent(url.pathname.slice(15)));if(url.pathname.startsWith("/api/auth/")){const r=await auth(req,env,url);if(r)return r}if(url.pathname.startsWith("/api/admin/")||url.pathname.startsWith("/api/users")){const s=await session(req,env);if(!s)return json({error:"Unauthorized"},401);if(req.method!=="GET"&&!csrf(req,s))return json({error:"Invalid CSRF token."},403);if(url.pathname.startsWith("/api/users")){const r=await users(req,env,url,s);if(r)return r}if(url.pathname.startsWith("/api/admin/gallery")){const r=await galleryAdmin(req,env,url);if(r)return r}if(url.pathname==="/api/admin/content"&&req.method==="GET")return json(await getContent(env));if(url.pathname==="/api/admin/content"&&req.method==="PUT")return json(await saveContent(env,await req.json()));if(url.pathname==="/api/admin/reset"&&req.method==="POST")return json(await saveContent(env,await defaults(env)))}if((url.pathname==="/admin"||url.pathname==="/admin/")&&!await session(req,env))return Response.redirect(`${url.origin}/admin/login/`,302);if(url.pathname==="/admin/users"||url.pathname==="/admin/users/"){const s=await session(req,env);if(!s)return Response.redirect(`${url.origin}/admin/login/`,302);if(!superAdmin(s.email))return new Response("Forbidden",{status:403})}return env.ASSETS.fetch(req)}};
